spring:
  profiles:
    active: secret

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # name: xxx-druid
      url: ${secret.spring.datasource.druid.url}
      username: ${secret.spring.datasource.druid.username}
      password: ${secret.spring.datasource.druid.password}
      filters: stat,wall
      initialSize: 5
      maxActive: 20
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      web:
        username: ${secret.spring.datasource.druid.web.username}
        password: ${secret.spring.datasource.druid.web.password}
        resetEnable: false

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/html/
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

server:
  port: 9500
  servlet:
    context-path: /

mybatis:
  type-aliases-package: cn.ultronxr.**.bean.mybatis.bean
  mapper-locations: classpath:mapper/*.xml

shiro:
  session:
    # session 过期时间，单位：分钟
    timeout: 2
    # 定时清理无效的 session ，单位：分钟
    validationInterval: 10
  cookie:
    domain: ultronxr
    path: /
    # cookies 过期时间，单位：天
    maxAge: 1
    # 防止xss读取cookie
    httpOnly: true
    # cookie 加密key，使用 Base64.encodeToString(CipherUtils.generateNewKey(128, "AES").getEncoded()) 生成一个，粘贴在这里
    cipherKey: m1zjb+t/nactPz9H4Ie7BQ==
  rememberMe:
    # 是否启用记住登录功能
    enabled: false

