spring:
  profiles:
    active: secret, dev

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/html/
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

  security:
    user:
      name: USELESS_PLACEHOLDER
      password: USELESS_PLACEHOLDER

  redis:
    redisson:
      file: classpath:config/redisson.yml

server:
  port: 9500
  servlet:
    context-path: /

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  type-aliases-package: cn.ultronxr.**.bean.mybatis.bean
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
#      insert-strategy: not_empty
#      update-strategy: not_empty
      # 排除 select 时 Java Bean 属性值为空对 where 筛选条件的影响
      where-strategy: not_empty
  configuration:
    map-underscore-to-camel-case: true

# springboot actuator 配置，参见 {@link https://www.cnblogs.com/caoweixiong/p/15325382.html}
management:
  server:
    port: -1
  endpoints:
    # 关闭监控
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        # 开启所有的 endpoints (不包含shutdown)
        include: "*"
        exclude:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
