spring:
  profiles:
    active: secret

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # name: xxx-druid
      url: ${secret.spring.datasource.druid.url}
      username: ${secret.spring.datasource.druid.username}
      password: ${secret.spring.datasource.druid.password}
      filters: stat,wall
      initialSize: 5
      maxActive: 20
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      web:
        username: ${secret.spring.datasource.druid.web.username}
        password: ${secret.spring.datasource.druid.web.password}
        resetEnable: false

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/html/
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

server:
  port: 9500
  servlet:
    context-path: /

mybatis:
  type-aliases-package: cn.ultronxr.**.bean.mybatis.bean
  mapper-locations: classpath:mapper/*.xml
