spring:
  profiles:
    active: secret, dev

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/html/
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

server:
  port: 9500
  servlet:
    context-path: /

mybatis:
  type-aliases-package: cn.ultronxr.**.bean.mybatis.bean
  mapper-locations: classpath*:mapper/**/*.xml
