spring:
  profiles:
    active: secret, dev

  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /static/html/
      suffix: .html

  web:
    resources:
      static-locations: classpath:/static/,classpath:/templates/

  redis:
    redisson:
      file: classpath:conf/redisson.yml

server:
  port: 9500
  servlet:
    context-path: /

logging:
  level:
    cn.ultronxr.*.bean.mybatis.mapper: debug

mybatis:
  type-aliases-package: cn.ultronxr.**.bean.mybatis.bean
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springboot actuator 配置，参见 {@link https://www.cnblogs.com/caoweixiong/p/15325382.html}
management:
  server:
    port: -1
  endpoints:
    # 关闭监控
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        # 开启所有的 endpoints (不包含shutdown)
        include: "*"
        exclude:
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: always
